### ISSUE TITLE
Dies with error Wrong type argument: processp, nil

### ISSUE THREAD

**Issue by brandon-rhodes** [syohex/emacs-git-gutter-fringe#22]
I just installed `git-gutter-fringe` for the first time by running the following commands in `*scratch*`:
```
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("melpa" . "http://melpa.milkbox.net/packages/")
        ))
(("gnu" . "http://elpa.gnu.org/packages/") ("melpa" . "http://melpa.milkbox.net/packages/"))

(package-initialize)
t

(package-refresh-contents)
nil

(package-install 'git-gutter-fringe)
nil
```
I then opened a file that is under `git` version control, ran `M-x git-gutter`, and received the error:
```
git-gutter:start-diff-process: Wrong type argument: processp, nil
```
Is there any way to get a more detailed traceback so that I can learn what, exactly, went wrong?

**Comment by syohex** [comment]
It's bug. Currently git-gutter works only when git-gutter-mode is enabled.
I'll fix later.

You can use git-gutter by enabling `git-gutter-mode` or `global-git-gutter`mode`.
```lisp
(global-git-gutter-mode +1)
```

**Comment by syohex** [comment]
I fixed at https://github.com/syohex/emacs-git-gutter/pull/85.
Please update git-gutter version.

**Comment by syohex** [comment]
Please reopen if you still have problems.
Thanks for reporting issue.

**Comment by brandon-rhodes** [comment]
Wow — incredible response time — only a few hours from my reporting the bug to a new version being available! And the fix worked perfectly, and I am now happily using git-gutter for the first time. Thank you!
