### ISSUE TITLE
[feature request] implements highlighting changes on the fly.

### ISSUE THREAD

**Issue by zw963** [syohex/emacs-git-gutter-fringe#27]
enables diffing on-the-fly (i.e. without saving the buffer first)

thanks

**Comment by syohex** [comment]
Please use `git-gutter:update-interval` same as `git-gutter`.

**Comment by zw963** [comment]
It worked, sorry.

But there exist a problem:

when add some code to buffer, it is seem like more CPU usage
to make current laptop lags. even in this way, sign is still not
real-time update for me.

**Comment by syohex** [comment]
You need to wait some hours until MELPA updating. Or use latest git-gutter.el

**Comment by zw963** [comment]
real-time update is worked. thanks.

**Comment by zw963** [comment]
But here exist a little bother, if current buffer changed line is several hundred line, 
input code is lags, see top, emacs always have a very high usage in this time.

**Comment by syohex** [comment]
It runs git command every `git-gutter:update-interval` second and some emacs lisp code. So it makes slow.
