### ISSUE TITLE
Not worked with nlinum-mode.

### ISSUE THREAD

**Issue by zw963** [syohex/emacs-git-gutter-fringe#32]
Before save, it worked as follow:

![Screenshot from 2017-12-05 18-51-17.png](http://zw963.github.io/images/4337283622923.png)

After C-x C-s, save buffer, it change to: 

![Screenshot from 2017-12-05 18-53-07.png](http://zw963.github.io/images/242573226723660.png)

If maximize frame window and then restore, it display normal again.

https://github.com/emacsmirror/nlinum

thanks

**Comment by zw963** [comment]
Try to use emacs builtin `linum-mode` now, it worked.

**Comment by tigerk0430** [comment]
or  try 
`(setq git-gutter:window-width 5)`
It worked for me

**Comment by zw963** [comment]
Thanks
