### ISSUE TITLE
No characters, only bars.

### ISSUE THREAD

**Issue by matthewpersico** [syohex/emacs-git-gutter-fringe#37]
Updated to emacs 27.2 using libXaw instead of GTK. The +,- indicators are replaced with colored bars. Any idea where to start diagnosing?

The little red triangle is the deleted line indicator.
![image](https://user-images.githubusercontent.com/3129206/152472411-c1bebf34-e251-4133-8a13-3d1ce9713db3.png)

The yellow bar is the added line indicator and the purple bar is the modified line indicator
![image](https://user-images.githubusercontent.com/3129206/152472548-2450f5e2-5dcf-4edc-9045-f34ac6a9f96a.png)

**Comment by syohex** [comment]
I cannot reproduce your issue. Is this your configuration issue ? Please removing all git-gutter/git-gutter-fringe configurations and retry.

![Screenshot from 2022-02-04 15-02-34](https://user-images.githubusercontent.com/554281/152481635-28ea8e39-9844-437b-ab98-adcb96a6e8fb.png)

**Comment by matthewpersico** [comment]
I will try and then get back to you. It may take a few days. Thank you for replying.

**Comment by matthewpersico** [comment]
I am using a theme that is very complicated. I ended up adding the following to my initialization
```lisp
(fringe-helper-define 'git-gutter-fr:added nil
  "...XX..."
  "...XX..."
  "...XX..."
  "XXXXXXXX"
  "XXXXXXXX"
  "...XX..."
  "...XX..."
  "...XX...")
(set-face-foreground 'git-gutter-fr:added    "green")

(fringe-helper-define 'git-gutter-fr:modified nil
  "........"
  "........"
  "..XX...."
  ".XXXX..X"
  "X..XXXX."
  "....XX.."
  "........"
  "........")
(set-face-foreground 'git-gutter-fr:modified   "yellow")

(fringe-helper-define 'git-gutter-fr:deleted nil
   "........"
  "........"
  "........"
  "XXXXXXXX"
  "XXXXXXXX"
  "........"
  "........"
  "........")
(set-face-foreground 'git-gutter-fr:deleted    "red")
```
which results in:
![image](https://user-images.githubusercontent.com/3129206/152616021-90dd3a54-9cf1-4113-8fad-78dea7628c68.png)

which is good enough for me.
